import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { InheritanceCase, Heir, Asset, FaraidResult } from './types';

interface ExportPayload {
  caseData: InheritanceCase;
  heirs: Heir[];
  assets: Asset[];
  result: FaraidResult | null;
  t: (k: string) => string;
}

export function exportPDF({ caseData, heirs, assets, result, t }: ExportPayload) {
  const doc = new jsPDF();
  doc.setFontSize(20);
  doc.text('GadoPro — Inheritance Report', 14, 18);
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(`Deceased: ${caseData.deceased_name}`, 14, 28);
  if (caseData.deceased_date) doc.text(`Date: ${caseData.deceased_date}`, 14, 34);
  doc.text(`Total Estate: ${caseData.total_estate.toLocaleString()}`, 14, 40);
  doc.text(`Status: ${caseData.status}`, 14, 46);

  let y = 56;
  if (assets.length) {
    doc.setTextColor(0);
    doc.setFontSize(13);
    doc.text('Assets', 14, y);
    autoTable(doc, {
      startY: y + 3,
      head: [['Type', 'Description', 'Value']],
      body: assets.map(a => [a.type, a.description, a.value.toLocaleString()]),
      theme: 'striped',
      headStyles: { fillColor: [22, 122, 92] },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  }

  if (heirs.length) {
    doc.setFontSize(13);
    doc.text('Heirs', 14, y);
    autoTable(doc, {
      startY: y + 3,
      head: [['Name', 'Relationship']],
      body: heirs.map(h => [h.name, h.relationship.replace(/_/g, ' ')]),
      theme: 'striped',
      headStyles: { fillColor: [22, 122, 92] },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  }

  if (result) {
    doc.setFontSize(13);
    doc.text('Faraid Distribution', 14, y);
    autoTable(doc, {
      startY: y + 3,
      head: [['Heir', 'Relationship', 'Fraction', '%', 'Amount']],
      body: result.heirs.map(h => [
        h.name, h.relationship.replace(/_/g, ' '), h.fraction,
        `${h.percentage}%`, h.amount.toLocaleString(),
      ]),
      foot: [['', '', '', t('calculation.totalDistributed'), result.total_distributed.toLocaleString()]],
      theme: 'striped',
      headStyles: { fillColor: [22, 122, 92] },
      footStyles: { fillColor: [240, 240, 240], textColor: 0, fontStyle: 'bold' },
    });
  }

  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text(`Generated by GadoPro on ${new Date().toLocaleDateString()}`, 14, doc.internal.pageSize.height - 10);

  doc.save(`GadoPro-${caseData.deceased_name.replace(/\s+/g, '_')}.pdf`);
}

export function exportExcel({ caseData, heirs, assets, result }: ExportPayload) {
  const wb = XLSX.utils.book_new();

  const summary = [
    ['GadoPro Inheritance Report'],
    [],
    ['Deceased', caseData.deceased_name],
    ['Date', caseData.deceased_date],
    ['Total Estate', caseData.total_estate],
    ['Status', caseData.status],
    ['Notes', caseData.notes],
  ];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(summary), 'Summary');

  if (assets.length) {
    const aoa = [['Type', 'Description', 'Value'], ...assets.map(a => [a.type, a.description, a.value])];
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(aoa), 'Assets');
  }

  if (heirs.length) {
    const aoa = [['Name', 'Relationship'], ...heirs.map(h => [h.name, h.relationship])];
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(aoa), 'Heirs');
  }

  if (result) {
    const aoa = [
      ['Heir', 'Relationship', 'Fraction', 'Percentage', 'Amount'],
      ...result.heirs.map(h => [h.name, h.relationship, h.fraction, h.percentage, h.amount]),
      [],
      ['Total Distributed', '', '', '', result.total_distributed],
      ['Remainder', '', '', '', result.remainder],
    ];
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(aoa), 'Distribution');
  }

  XLSX.writeFile(wb, `GadoPro-${caseData.deceased_name.replace(/\s+/g, '_')}.xlsx`);
}
